name: "grid_pulse_spain"
version: "1.0.0"
config-version: 2

profile: "grid_pulse_spain"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  grid_pulse_spain:
    staging:
      +materialized: view
    marts:
      +materialized: table
